name: my-storage-project
metadata:
  template: false
  description: "Storage account with text files"
infra:
  provider: "bicep"
  path: "./infra"
hooks:
  postdeploy:
    windows:
      shell: pwsh
      run: ./hooks/postdeploy.ps1
      interactive: true
      continueOnError: false
pipeline:
  provider: "azdo"